[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "titan_os.json"


[target.'cfg(target_os = "none")']
runner = "bootimage runner"
